startupsuccess/urls.py
"""startupsuccess URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    # 1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# date = timezone.now()
#   print()
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from config.views import *
from ecosystem.views import *
from journal.views import *

# from material.admin import urls

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('accounts/', include('allauth.urls')),

        path('__debug__/', include(debug_toolbar.urls)),

        # path('profile/', MentorProfileDetailView.as_view(), name='myprofile'),
        # path('profile/<slug>/bio/add/', ProfileBio.as_view(), name='profile-bio'),
        
        #new user
        path('profile/<slug>/create', CreateProfile.as_view(), name='profile_create'),
        path('profile/<slug>/experience/', CreateProfileExperience.as_view(), name='profile_create_experience'),
        path('profile/<slug>/education/', CreateProfileEducation.as_view(), name='profile_create_education'),
        path('profile/<slug>/skill/', CreateProfileSkill.as_view(), name='profile_create_skill'),
        
        path('entities-role/', RoleEntitiesView.as_view(), name='role-entities'),
        path('mentor/add/', MentorAdd.as_view(), name='mentor-add'),
        path('mentor/qualification/', MentorQualification.as_view(), name='qualification_mentor'),
        path('mentor/qualification/add/', MentorQualificationAnswer.as_view(), name='qualification_add_mentor'),
        path('mentor/qualification/status/', MentorQualificationStatus.as_view(), name='qualification_status_mentor'),
        path('startup-role/', RoleStartupView.as_view(), name='role-startup'),
        path('startup/add/', StartupAdd.as_view(), name='startup-add'),


        #profile
        path('profile/<slug>/', ProfileView.as_view(), name='myprofile'),
        path('profile/<slug>/update/', ProfileUpdate.as_view(), name='profile-update-profile'),
        path('profile/<slug>/experience/add/', ProfileExperienceAdd.as_view(), name='profile_add_experience'),
        path('profile/<slug>/<pk>/experience/update/', ProfileExperienceUpdate.as_view(), name='profile_update_experience'),
        path('profile/<slug>/<pk>/experience/delete/', ProfileExperienceDelete.as_view(), name='profile_delete_experience'),
        path('profile/<slug>/education/add/', ProfileEducationAdd.as_view(), name='profile_add_education'),
        path('profile/<slug>/<pk>/education/update/', ProfileEducationUpdate.as_view(), name='profile_update_education'),
        path('profile/<slug>/<pk>/education/delete/', ProfileEducationDelete.as_view(), name='profile_delete_education'),
        path('profile/<slug>/skill/add', ProfileSkillAdd.as_view(), name='profile_add_skill'),
        path('profile/<slug>/<pk>/skill/update/', ProfileSkillUpdate.as_view(), name='profile_update_skill'),
        path('profile/<slug>/<pk>/skill/delete/', ProfileSkillDelete.as_view(), name='profile_delete_skill'),

        # path('profile/<slug>/update', ProfileUserUpdate.as_view(), name='profile-update-user'),


        #schedule
        path('schedule/', ScheduleListView.as_view(), name='schedule-list'),
        path('schedule/update/mentor/<slug>/<pk>/', ScheduleMentorAttendanceUpdate.as_view(), name='schedule_update_attendance_mentor'),
        path('schedule/update/startup/<slug>/<pk>/', ScheduleStartupAttendanceUpdate.as_view(), name='schedule_update_attendance_startup'),

        #mentoring
        path('mentor/<slug>/mentoring/add', MentorMentoringAdd.as_view(), name='mentor-add-mentoring'),
        path('mentor/<slug>/<pk>/mentoring/note', MentorMentoringNote.as_view(), name='mentoring_add_note'),
        path('startup/<slug>/<pk>/update/mentoring', StartupUpdateMentoring.as_view(), name='startup-update-mentoring'),

        #feedback
        path('mentoring/<pk>/feedback/add/startup/', StartupFeedbackForMentor.as_view(), name='startup-feedback'),
        path('mentoring/<pk>/feedback/add/mentor/', MentorFeedbackForStartup.as_view(), name='mentor-feedback'),

        #task
        path('mentor/<pk>/task/add', MentorTaskAdd.as_view(), name='mentor_add_task'),



        # path('startup/<slug>/mentoring/add', StartupMentoringAdd.as_view(), name='startup-add-mentoring'),



        # path('profile/<slug>/', ProfileExperienceAdd.as_view(), name='profile_experience_add'),

        # path('profile/<slug>/', ProfileView.as_view(), name='myprofile'),
        path('profile/<slug>/<pk>/', ApprovalMemberView.as_view(), name='approval-startup'),
        #2
        path('mentor/', MentorListView.as_view(), name='mentor-list'),
        path('mentor/<slug>/add/', MentorUpdateSkillsView.as_view(), name='mentor-update-skills'),
        #3
        # path('mentor/<slug>/', MentorDetailView.as_view(), name='mentor-detail'),
        path('mentor/<pk>/', MentorDetailView.as_view(), name='mentor-detail'),

        #4
        path('mentor/<slug>/generate-pdf', GenerateMentorPdf.as_view(), name='generate-mentor-pdf'),
        path('mentor/<slug>/update/', MentorUpdateView.as_view(), name='mentor-update'),
        path('mentor/<slug>/<pk>/update/mentoring', MentorUpdateMentoring.as_view(), name='mentor-update-mentoring'),
        path('mentor/<slug>/mentoring-detail', MentorMentoringDetail.as_view(), name='mentor-mentoring-detail'),

        path('member/invite/', MemberListView.as_view(), name='member-invite'),
        path('member/invite/<pk>', RequestInviteMemberView.as_view(), name='request-invite'),

        path('startup-role/requestjoin/<slug>', RequestJoinView.as_view(), name='join-startup'),

        path('startup/<slug>/<int:pk>/', ApprovalView.as_view(), name='approval-member' ),
        #0
        #6
        path('startup/', StartupListView.as_view(), name='startup-list'),
        path('startup/<slug>/', StartupDetailView.as_view(), name='startup-detail'),
        path('startup/<slug>/generate-pdf', GenerateStartupPdf.as_view(), name='generate-startup-pdf'),
        path('startup/<slug>/update/', StartupUpdate.as_view(), name='startup-update'),
        path('startup/<slug>/<pk>/mentoring-detail', StartupMentoringDetailView.as_view(), name='startup-mentoring-detail'),
        path('startup/<slug>/<pk>/add/answer-task', StartupMentoringAddTask.as_view(), name='startup-add-mentoring-task'),
        path('startup/<slug>/delete/', StartupDelete.as_view(), name='startup-delete'),
        path('startup/<slug>/add-progress', StartupAddProgress.as_view(), name='startup-add-progress'),
        path('startup/<slug>/<pk>/detail/progress', StartupDetailProgress.as_view(), name='startup-detail-progress'),
        path('startup/<slug>/<pk>/update/progress', StartupUpdateProgress.as_view(), name='startup-update-progress'),
        path('startup/<slug>/<pk>/delete/progress', StartupDeleteProgress.as_view(), name='startup-delete-progress'),
        path('startup/<slug>/<pk>/schedule-detail', StartupScheduleDetailView.as_view(), name='startup-schedule-detail'),

        path('mentoring/', MentoringListView.as_view(), name='mentoring-list'),
        path('mentoring/add/', MentoringCreateView.as_view(), name='mentoring-add'),
        path('mentoring/generate-pdf', GenerateMentoringPdf.as_view(), name='generate-mentoring-pdf'),
        #5
        path('mentoring/<pk>/', MentoringDetailView.as_view(), name='mentoring-detail'),
        path('mentoring/<pk>/attendance/', MentoringAttendance.as_view(), name='mentoring-attendance'),

        path('mentoring/<pk>/feedback', MentoringFeedback.as_view(), name='mentoring-feedback'),
        
        path('mentoring/<pk>/delete/', MentoringDeleteView.as_view(), name='mentoring-delete'),
        path('mentoring/<pk>/update/startup', MentoringUpdateStartupView.as_view(), name='mentoring-update-startup'),
        path('mentoring/<pk>/update/mentor', MentoringUpdateMentorView.as_view(), name='mentoring-update-mentor'),


        #1
        path('', HomeView.as_view(), name='home'),

        path(r'jet/', include('jet.urls', 'jet')),  # Django JET URLS
        # path('')
        path('invitations/', include('invitations.urls', namespace='invitations')),
        path('member/invite/email/', InviteEmailMemberView.as_view(), name='member-invite-email'),


    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/models.py
import json
import datetime
import uuid
from django.utils import timezone
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.urls import reverse

class Program(models.Model):
  name = models.CharField(max_length=255)
  description = models.TextField()
  slug = models.SlugField(max_length=128, blank=True)

  def __str__(self):
    return self.slug

  def save(self, *args, **kwargs):
    if self.slug is '' or self.slug is None:
      self.slug = slugify(self.name)
    super().save(*args, **kwargs)

"""
COMMON DATA
"""

class SkillData(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  profile = models.ForeignKey('ecosystem.Profile', blank=True, null=True, on_delete=models.CASCADE)
  name = models.CharField(max_length=255,)

  def __str__(self):
      return self.name

  def get_absolute_url(self):
    return reverse('myprofile', args=[str(self.profile.slug)])
  
class ExperienceData(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  profile = models.ForeignKey('ecosystem.Profile', blank=True, null=True, on_delete=models.CASCADE)
  title = models.CharField(max_length=255,)
  company = models.CharField(max_length=255, )
  location = models.URLField(max_length=255, blank=True)
  enroll_date = models.DateField(blank=True, null=True, default=timezone.now,)
  graduate_date = models.DateField(blank=True, null=True, default=timezone.now,)
  description = RichTextField(blank=True)
  is_current = models.BooleanField(default=False)

  def __str__(self):
      return self.title + ' -- ' + self.company

  def get_absolute_url(self):
    return reverse('myprofile', args=[str(self.profile.slug)])

class EducationData(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  profile = models.ForeignKey('ecosystem.Profile', blank=True, null=True, on_delete=models.CASCADE)
  name = models.CharField(max_length=255,)
  department = models.CharField(max_length=255,)
  year = models.PositiveIntegerField()

  def __str__(self):
      return self.name + ' -- ' + self.department + ' -- ' + self.year.__str__()

  def get_absolute_url(self):
    return reverse('myprofile', args=[str(self.profile.slug)])

journal/models.py
import json
import datetime
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.utils.text import slugify
from django.db import models
from django.db.models.signals import m2m_changed
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.auth.models import User
from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from ckeditor.fields import RichTextField
from util.randomizer import unique_slug_generator, unique_slug_generator_byfield
from config.models import *
from django.urls import reverse


class Scheduling(models.Model):
  program = models.ForeignKey('config.Program', on_delete=models.CASCADE)
  description = RichTextField(blank=True)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ManyToManyField('ecosystem.Startup')
  venue  = models.CharField(max_length=255, default='Common Room')
  capacity = models.CharField(max_length=255, blank=True)
  datetime = models.DateTimeField(default=timezone.now)
  location = models.CharField(max_length=255, default='EDS')
  status_mentor = models.BooleanField(default=False)
  status_startup = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.program.name

class Mentoring(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  program = models.ForeignKey('config.Program', on_delete=models.CASCADE)
  datetime = models.DateTimeField(default=timezone.now)
  title = models.CharField(max_length=255)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE, blank=True)
  # mentor_attendance = models.BooleanField(default=True)
  # founder_attendance = models.ManyToManyField('ecosystem.StartupMember', related_name='founder_attendance', blank=True)
  mentor_question = RichTextField(blank=True)
  startup_answer = RichTextField(blank=True)
  startup_question = RichTextField(blank=True)
  mentor_answer = RichTextField(blank=True)
  mentor_notes = RichTextField(blank=True)
  startup_notes = RichTextField(blank=True)
  location = models.CharField(max_length=255, default='EDS')

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.id)])

  def __str__(self):
      return self.title

class Task(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE)
  task_for_startup = RichTextField(blank=True)
  startup_assignment_report = RichTextField(blank=True)
  mentor_assignment_feedback = RichTextField(blank=True)
  
  def __str__(self):
    return self.task_for_startup


class FeedbackForMentor(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  communication_grade = models.PositiveIntegerField()
  relevance_grade = models.PositiveIntegerField()
  helpfullness_grade = models.PositiveIntegerField()
  note = RichTextField(blank=True)

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.mentoring.id)])

  # def __str__(self):
  #   return self.note

class FeedbackForStartup(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  communication_grade = models.PositiveIntegerField()
  attitude_grade = models.PositiveIntegerField()
  perseverance_grade = models.PositiveIntegerField()
  note = RichTextField(blank=True)

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.mentoring.id)])


def startupprogress_directory_path(instance, filename):
  return 'startupprogress/{0}/{1}'.format(instance.startup.name,filename)

class StartupProgress(models.Model):
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE)
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  week = models.PositiveIntegerField()
  acquisition = models.PositiveIntegerField()
  picture_acquisition = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_acquisition = models.URLField(max_length=255, blank=True)
  activation = models.PositiveIntegerField()
  picture_activation = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_activation = models.URLField(max_length=255, blank=True)
  retention = models.PositiveIntegerField()
  picture_retention = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_retention = models.URLField(max_length=255, blank=True)
  revenue = models.PositiveIntegerField()
  picture_revenue = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_revenue = models.URLField(max_length=255, blank=True)  
  referral = models.PositiveIntegerField()
  picture_referral = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_referral = models.URLField(max_length=255, blank=True)
  note = RichTextField(blank=True)
  datetime = models.DateTimeField(default=timezone.now)

  def get_absolute_url(self):
    return reverse('startup-detail', args=[str(self.startup.slug)])

templates/mentoring/detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% load social_share %}
{% block title %}StartupSuccess{% endblock %}

{% block content %}

<div class="my-3 my-md-5">
    <div class="container">
        
        <div class="page-header">
            <h1 class="page-title">Details</h1>
        </div>

        <div class="col-lg-12">
            <div class="card">
        
                <div class="card-header">
                    <h3 class="card-title">{{dataMentoring}}</h3>
                    <div class="card-options">
                        <a href="{% url 'mentoring-feedback' pk=mentoring.id %}" class="btn btn-primary btn-sm"><i class="fa fa-comments mr-2"></i>  Feedback</a>
                    </div>
                </div>
        
                <div class="table-responsive">
                    <table class="table card-table table-striped table-vcenter">
                        <thead>
                            <tr>
                                <th colspan="2">Speaker</th>
                                <th>Time</th>
                                <th>Location</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="w-1">
                                {% if dataMentoring.mentor.mentor.profile.picture %}
                                    <span class="avatar" style="background-image: url('/media/{{dataMentoring.mentor.mentor.profile.picture}}')"></span>
                                {% else %}
                                    <span class="avatar" style="background-image: url(/static/demo/faces/male/user.png)"></span>
                                {% endif %}

                                    <td>{{dataMentoring.mentor}}</td>
                                    <td class="text-nowrap">{{dataMentoring.datetime}}</td>
                                    <td>{{dataMentoring.location}}</td>
                                          
                                    <td class="w-1"><a href="#" class="btn btn-sm btn-secondary" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><i class="fe fe-upload mr-1"></i> Share</a>
                                    <div class="collapse" id="collapseExample">
                                            {% post_to_twitter "New Mentoring: {{dataMentoring}}. Check it out!" object_or_url "Twitter" %}
                                            {% post_to_facebook  object_or_url "Facebook" %}

                                        </div>
                                    </td>
                                    
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="card-footer">
                    <h3 class="card-title">Description</h3>
                    <p>{{dataMentoring.program.description}}</p>
                </div>

                <div class="card-body">
                 <h3 class="card-title">Notes</h3>
                            <table class="table table-bordered">                    
                                <tbody>
                                    <tr>
                                        <td rowspan="4" width="150px">
                                            <div class="text-center">
                                                <span>{{dataMentoring.datetime}}</span>
                                                {% comment %} <span class="bulan">April</span><br>
                                                <span class="tanggal">10</span><br>
                                                <span class="jam">04.00 pm - 07.00 pm</span>                                            {% endcomment %}
                                            </div>
                                        </td>
                                        <td colspan="3">{{dataMentoring.mentor}}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">
                                            {{dataMentoring.mentor_notes}}
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">{{dataMentoring.startup}}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">
                                            {{ dataMentoring.startup_notes }}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                            {% comment %} <div class="text-center">
                            {% if startupedit %}
                                <a href='{% url "mentoring-update-startup" pk=dataMentoring.id %}'  class="btn btn-warning"><i class="fe fe-edit mr-1"></i> Edit</a>
                            {% else %}
                                <a href='{% url "mentoring-update-mentor" pk=dataMentoring.id %}'  class="btn btn-warning"><i class="fe fe-edit mr-1"></i> Edit</a>
                            {% endif %}
                            </div> {% endcomment %}
                        </div>
                
                <div class="card-body">
                    <div class="card">
                        {% for feedback in dataMentoring.feedbackformentor_set.all %}
                        <div class="card-body">
                            {% comment %} <div class=""> {% endcomment %}
                            <h3 class="card-title">Feedback From Startup</h3>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="h5">
                                            Communication: {{feedback.communication_grade}} 
                                        </div>
                                        <div class="progress progress-sm">
                                            <div class="progress-bar {% if feedback.communication_grade < 60 %} bg-red {% elif feedback.communication_grade < 80%} bg-yellow {% else %} bg-green {% endif %}" style="width: {{feedback.communication_grade}}%"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="h5">
                                            Relevance: {{feedback.relevance_grade}}
                                        </div>
                                        <div class="progress progress-sm">
                                            <div class="progress-bar {% if feedback.relevance_grade < 60 %} bg-red {% elif feedback.relevance_grade < 80%} bg-yellow {% else %} bg-green {% endif %}" style="width: {{feedback.relevance_grade}}%"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="h5">
                                            Helpfullness: {{feedback.helpfullness_grade}}
                                        </div>
                                        <div class="progress progress-sm">
                                            <div class="progress-bar {% if feedback.helpfullness_grade < 60 %} bg-red {% elif feedback.helpfullness_grade < 80%} bg-yellow {% else %} bg-green {% endif %}" style="width: {{feedback.helpfullness_grade}}%"></div>
                                        </div>
                                    </div>
                                </div>
                            {% comment %} </div> {% endcomment %}
                        </div>
                        <div class="card-body">
                            <p>{{feedback.note}}</p>
                        </div>
                            {% endfor %}
                            
                            {% for feedback in dataMentoring.feedbackforstartup_set.all %}
                        <div class="card-body">
                            {% comment %} <div class=""> {% endcomment %}
                            <h3 class="card-title">Feedback From Mentor</h3>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="h5">
                                            Communication: {{feedback.communication_grade}} 
                                        </div>
                                        <div class="progress progress-sm">
                                            <div class="progress-bar {% if feedback.communication_grade < 60 %} bg-red {% elif feedback.communication_grade < 80%} bg-yellow {% else %} bg-green {% endif %}" style="width: {{feedback.communication_grade}}%"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="h5">
                                            Attitude: {{feedback.attitude_grade}}
                                        </div>
                                        <div class="progress progress-sm">
                                            <div class="progress-bar {% if feedback.attitude_grade < 60 %} bg-red {% elif feedback.attitude_grade < 80%} bg-yellow {% else %} bg-green {% endif %}" style="width: {{feedback.attitude_grade}}%"></div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="h5">
                                            Perseverance: {{feedback.perseverance_grade}}
                                        </div>
                                        <div class="progress progress-sm">
                                            <div class="progress-bar {% if feedback.perseverance_grade < 60 %} bg-red {% elif feedback.perseverance_grade < 80%} bg-yellow {% else %} bg-green {% endif %}" style="width: {{feedback.perseverance_grade}}%"></div>
                                        </div>
                                    </div>
                                </div>
                            {% comment %} </div> {% endcomment %}
                        </div>
                        <div class="card-body">
                            <p>{{feedback.note}}</p>
                        </div>
                            {% endfor %}
                    </div>

                </div>

                

                {% comment %} <div class="card-footer">
                    <h3 class="card-title">Task</h3>
                    <p>{{dataMentoring.program.description}}</p>
                    <p> {{dataMentoring.task_for_startup}} </p>
                </div> {% endcomment %}

                {% comment %} <div class="card-body"> {% endcomment %}
                    {% comment %} <h3 class="card-title"> Startup Attendance <span>(20)</span> </h3> {% endcomment %}
                
                   {% comment %} <div class="row row-cards row-deck"> {% endcomment %}
                    {% comment %} <div class="col-sm-6 col-xl-3">
                        <div class="card">
                            <a href="#"><img class="card-img-top" src="/static/demo/photos/david-klaasen-54203-500.jpg" alt="And this isn&#39;t my nose. This is a false one."></a>
                            <div class="card-body d-flex flex-column">
                                <h4><a href="#">Name of Startup</a></h4>
                                <div class="text-muted"></div>
                            
                                </div>
                            </div>
                        </div>
                    </div> {% endcomment %}
                    {% comment %} <div class="col text-center">
                    <a href="{% url 'mentoring-attendance' pk=dataMentoring.id  %}" class="btn btn-primary" role="button">See all</a>
                    </div> {% endcomment %}
                    {% comment %} </div> {% endcomment %}
                {% comment %} </div> {% endcomment %}



                
        </div>
    </div>
</div>
<script>
$(function () {
  $('.example-popover').popover({
    container: 'body'
  })
})
</script>

{% endblock %}

templates/mentoring/feedback_for_mentor.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="my-3 my-md-5">
    <!--container-->
   <div class="container">

        <div class="card">
            
            <div class="card-header">
                <h3 class="card-title"> Feedback for Mentor </h3>
            </div>
        
            <div class="card-body">
                <form action="" method="post" class="">
                    {% csrf_token %}
                    <div class="form-group row">
                        <div class="col-6">
                           
                            <div class="card-content">
                                {{ form|crispy }}
                            </div>
                           
                            <div class="card-action">
                                <input type="submit" value="Save" class="btn btn-success" />
                            </div>
            
                        </div>
                    </div>        
                </form>
            </div>
   </div>
</div>
</div>
{% endblock %}

templates/mentoring/feedback_for_startup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="my-3 my-md-5">
    <!--container-->
   <div class="container">

        <div class="card">
            
            <div class="card-header">
                <h3 class="card-title"> Feedback for Startup </h3>
            </div>
        
            <div class="card-body">
                <form action="" method="post" class="">
                    {% csrf_token %}
                    <div class="form-group row">
                        <div class="col-6">
                           
                            <div class="card-content">
                                {{ form|crispy }}
                            </div>
                           
                            <div class="card-action">
                                <input type="submit" value="Save" class="btn btn-success" />
                            </div>
            
                        </div>
                    </div>        
                </form>
            </div>
   </div>
</div>
</div>
{% endblock %}