startupsuccess/urls.py
"""startupsuccess URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    # 1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# date = timezone.now()
#   print()
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from config.views import *
from ecosystem.views import *
from journal.views import *

# from material.admin import urls

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('accounts/', include('allauth.urls')),

        path('__debug__/', include(debug_toolbar.urls)),

        # path('profile/', MentorProfileDetailView.as_view(), name='myprofile'),
        # path('profile/<slug>/bio/add/', ProfileBio.as_view(), name='profile-bio'),
        
        #new user
        path('profile/<slug>/create', CreateProfile.as_view(), name='profile_create'),
        path('profile/<slug>/experience/', CreateProfileExperience.as_view(), name='profile_create_experience'),
        path('profile/<slug>/education/', CreateProfileEducation.as_view(), name='profile_create_education'),
        path('profile/<slug>/skill/', CreateProfileSkill.as_view(), name='profile_create_skill'),
        
        path('entities-role/', RoleEntitiesView.as_view(), name='role-entities'),
        path('mentor/add/', MentorAdd.as_view(), name='mentor-add'),
        path('mentor/qualification/', MentorQualification.as_view(), name='qualification_mentor'),
        path('mentor/qualification/add/', MentorQualificationAnswer.as_view(), name='qualification_add_mentor'),
        path('mentor/qualification/status/', MentorQualificationStatus.as_view(), name='qualification_status_mentor'),
        path('startup-role/', RoleStartupView.as_view(), name='role-startup'),
        path('startup/add/', StartupAdd.as_view(), name='startup-add'),


        #profile
        path('profile/<slug>/', ProfileView.as_view(), name='myprofile'),
        path('profile/<slug>/update/', ProfileUpdate.as_view(), name='profile-update-profile'),
        path('profile/<slug>/experience/add/', ProfileExperienceAdd.as_view(), name='profile_add_experience'),
        path('profile/<slug>/<pk>/experience/update/', ProfileExperienceUpdate.as_view(), name='profile_update_experience'),
        path('profile/<slug>/<pk>/experience/delete/', ProfileExperienceDelete.as_view(), name='profile_delete_experience'),
        path('profile/<slug>/education/add/', ProfileEducationAdd.as_view(), name='profile_add_education'),
        path('profile/<slug>/<pk>/education/update/', ProfileEducationUpdate.as_view(), name='profile_update_education'),
        path('profile/<slug>/<pk>/education/delete/', ProfileEducationDelete.as_view(), name='profile_delete_education'),
        path('profile/<slug>/skill/add', ProfileSkillAdd.as_view(), name='profile_add_skill'),
        path('profile/<slug>/<pk>/skill/update/', ProfileSkillUpdate.as_view(), name='profile_update_skill'),
        path('profile/<slug>/<pk>/skill/delete/', ProfileSkillDelete.as_view(), name='profile_delete_skill'),

        # path('profile/<slug>/update', ProfileUserUpdate.as_view(), name='profile-update-user'),


        #schedule
        path('schedule/', ScheduleListView.as_view(), name='schedule-list'),
        path('schedule/update/mentor/<slug>/<pk>/', ScheduleMentorAttendanceUpdate.as_view(), name='schedule_update_attendance_mentor'),
        path('schedule/update/startup/<slug>/<pk>/', ScheduleStartupAttendanceUpdate.as_view(), name='schedule_update_attendance_startup'),

        #mentoring
        path('mentor/<slug>/mentoring/add', MentorMentoringAdd.as_view(), name='mentor-add-mentoring'),
        path('mentor/<slug>/<pk>/mentoring/note', MentorMentoringNote.as_view(), name='mentoring_add_note'),
        path('startup/<slug>/<pk>/update/mentoring', StartupUpdateMentoring.as_view(), name='startup-update-mentoring'),

        #feedback
        path('mentoring/<pk>/feedback/add/startup/', StartupFeedbackForMentor.as_view(), name='startup-feedback'),
        path('mentoring/<pk>/feedback/add/mentor/', MentorFeedbackForStartup.as_view(), name='mentor-feedback'),

        #task
        path('mentor/<pk>/task/add', MentorTaskAdd.as_view(), name='mentor_add_task'),



        # path('startup/<slug>/mentoring/add', StartupMentoringAdd.as_view(), name='startup-add-mentoring'),



        # path('profile/<slug>/', ProfileExperienceAdd.as_view(), name='profile_experience_add'),

        # path('profile/<slug>/', ProfileView.as_view(), name='myprofile'),
        path('profile/<slug>/<pk>/', ApprovalMemberView.as_view(), name='approval-startup'),
        #2
        path('mentor/', MentorListView.as_view(), name='mentor-list'),
        path('mentor/<slug>/add/', MentorUpdateSkillsView.as_view(), name='mentor-update-skills'),
        #3
        # path('mentor/<slug>/', MentorDetailView.as_view(), name='mentor-detail'),
        path('mentor/<pk>/', MentorDetailView.as_view(), name='mentor-detail'),

        #4
        path('mentor/<slug>/generate-pdf', GenerateMentorPdf.as_view(), name='generate-mentor-pdf'),
        path('mentor/<slug>/update/', MentorUpdateView.as_view(), name='mentor-update'),
        path('mentor/<slug>/<pk>/update/mentoring', MentorUpdateMentoring.as_view(), name='mentor-update-mentoring'),
        path('mentor/<slug>/mentoring-detail', MentorMentoringDetail.as_view(), name='mentor-mentoring-detail'),

        path('member/invite/', MemberListView.as_view(), name='member-invite'),
        path('member/invite/<pk>', RequestInviteMemberView.as_view(), name='request-invite'),

        path('startup-role/requestjoin/<slug>', RequestJoinView.as_view(), name='join-startup'),

        path('startup/<slug>/<int:pk>/', ApprovalView.as_view(), name='approval-member' ),
        #0
        #6
        path('startup/', StartupListView.as_view(), name='startup-list'),
        path('startup/<slug>/', StartupDetailView.as_view(), name='startup-detail'),
        path('startup/<slug>/generate-pdf', GenerateStartupPdf.as_view(), name='generate-startup-pdf'),
        path('startup/<slug>/update/', StartupUpdate.as_view(), name='startup-update'),
        path('startup/<slug>/<pk>/mentoring-detail', StartupMentoringDetailView.as_view(), name='startup-mentoring-detail'),
        path('startup/<slug>/<pk>/add/answer-task', StartupMentoringAddTask.as_view(), name='startup-add-mentoring-task'),
        path('startup/<slug>/delete/', StartupDelete.as_view(), name='startup-delete'),
        path('startup/<slug>/add-progress', StartupAddProgress.as_view(), name='startup-add-progress'),
        path('startup/<slug>/<pk>/detail/progress', StartupDetailProgress.as_view(), name='startup-detail-progress'),
        path('startup/<slug>/<pk>/update/progress', StartupUpdateProgress.as_view(), name='startup-update-progress'),
        path('startup/<slug>/<pk>/delete/progress', StartupDeleteProgress.as_view(), name='startup-delete-progress'),
        path('startup/<slug>/<pk>/schedule-detail', StartupScheduleDetailView.as_view(), name='startup-schedule-detail'),

        path('mentoring/', MentoringListView.as_view(), name='mentoring-list'),
        path('mentoring/add/', MentoringCreateView.as_view(), name='mentoring-add'),
        path('mentoring/generate-pdf', GenerateMentoringPdf.as_view(), name='generate-mentoring-pdf'),
        #5
        path('mentoring/<pk>/', MentoringDetailView.as_view(), name='mentoring-detail'),
        path('mentoring/<pk>/attendance/', MentoringAttendance.as_view(), name='mentoring-attendance'),

        path('mentoring/<pk>/feedback', MentoringFeedback.as_view(), name='mentoring-feedback'),
        
        path('mentoring/<pk>/delete/', MentoringDeleteView.as_view(), name='mentoring-delete'),
        path('mentoring/<pk>/update/startup', MentoringUpdateStartupView.as_view(), name='mentoring-update-startup'),
        path('mentoring/<pk>/update/mentor', MentoringUpdateMentorView.as_view(), name='mentoring-update-mentor'),


        #1
        path('', HomeView.as_view(), name='home'),

        path(r'jet/', include('jet.urls', 'jet')),  # Django JET URLS
        # path('')
        path('invitations/', include('invitations.urls', namespace='invitations')),
        path('member/invite/email/', InviteEmailMemberView.as_view(), name='member-invite-email'),


    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/models.py
import json
import datetime
import uuid
from django.utils import timezone
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from django.urls import reverse

class Program(models.Model):
  name = models.CharField(max_length=255)
  description = models.TextField()
  slug = models.SlugField(max_length=128, blank=True)

  def __str__(self):
    return self.slug

  def save(self, *args, **kwargs):
    if self.slug is '' or self.slug is None:
      self.slug = slugify(self.name)
    super().save(*args, **kwargs)

"""
COMMON DATA
"""

class SkillData(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  profile = models.ForeignKey('ecosystem.Profile', blank=True, null=True, on_delete=models.CASCADE)
  name = models.CharField(max_length=255,)

  def __str__(self):
      return self.name

  def get_absolute_url(self):
    return reverse('myprofile', args=[str(self.profile.slug)])
  
class ExperienceData(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  profile = models.ForeignKey('ecosystem.Profile', blank=True, null=True, on_delete=models.CASCADE)
  title = models.CharField(max_length=255,)
  company = models.CharField(max_length=255, )
  location = models.URLField(max_length=255, blank=True)
  enroll_date = models.DateField(blank=True, null=True, default=timezone.now,)
  graduate_date = models.DateField(blank=True, null=True, default=timezone.now,)
  description = RichTextField(blank=True)
  is_current = models.BooleanField(default=False)

  def __str__(self):
      return self.title + ' -- ' + self.company

  def get_absolute_url(self):
    return reverse('myprofile', args=[str(self.profile.slug)])

class EducationData(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  profile = models.ForeignKey('ecosystem.Profile', blank=True, null=True, on_delete=models.CASCADE)
  name = models.CharField(max_length=255,)
  department = models.CharField(max_length=255,)
  year = models.PositiveIntegerField()

  def __str__(self):
      return self.name + ' -- ' + self.department + ' -- ' + self.year.__str__()

  def get_absolute_url(self):
    return reverse('myprofile', args=[str(self.profile.slug)])

journal/models.py
import json
import datetime
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.utils.text import slugify
from django.db import models
from django.db.models.signals import m2m_changed
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.auth.models import User
from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from ckeditor.fields import RichTextField
from util.randomizer import unique_slug_generator, unique_slug_generator_byfield
from config.models import *
from django.urls import reverse


class Scheduling(models.Model):
  program = models.ForeignKey('config.Program', on_delete=models.CASCADE)
  description = RichTextField(blank=True)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ManyToManyField('ecosystem.Startup')
  venue  = models.CharField(max_length=255, default='Common Room')
  capacity = models.CharField(max_length=255, blank=True)
  datetime = models.DateTimeField(default=timezone.now)
  location = models.CharField(max_length=255, default='EDS')
  status_mentor = models.BooleanField(default=False)
  status_startup = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.program.name

class Mentoring(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  program = models.ForeignKey('config.Program', on_delete=models.CASCADE)
  datetime = models.DateTimeField(default=timezone.now)
  title = models.CharField(max_length=255)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE, blank=True)
  # mentor_attendance = models.BooleanField(default=True)
  # founder_attendance = models.ManyToManyField('ecosystem.StartupMember', related_name='founder_attendance', blank=True)
  mentor_question = RichTextField(blank=True)
  startup_answer = RichTextField(blank=True)
  startup_question = RichTextField(blank=True)
  mentor_answer = RichTextField(blank=True)
  mentor_notes = RichTextField(blank=True)
  startup_notes = RichTextField(blank=True)
  location = models.CharField(max_length=255, default='EDS')

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.id)])

  def __str__(self):
      return self.title

class Task(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE)
  task_for_startup = RichTextField(blank=True)
  startup_assignment_report = RichTextField(blank=True)
  mentor_assignment_feedback = RichTextField(blank=True)
  
  def __str__(self):
    return self.task_for_startup


class FeedbackForMentor(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  communication_grade = models.PositiveIntegerField()
  relevance_grade = models.PositiveIntegerField()
  helpfullness_grade = models.PositiveIntegerField()
  note = RichTextField(blank=True)

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.mentoring.id)])

  # def __str__(self):
  #   return self.note

class FeedbackForStartup(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  communication_grade = models.PositiveIntegerField()
  attitude_grade = models.PositiveIntegerField()
  perseverance_grade = models.PositiveIntegerField()
  note = RichTextField(blank=True)

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.mentoring.id)])


def startupprogress_directory_path(instance, filename):
  return 'startupprogress/{0}/{1}'.format(instance.startup.name,filename)

class StartupProgress(models.Model):
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE)
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  week = models.PositiveIntegerField()
  acquisition = models.PositiveIntegerField()
  picture_acquisition = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_acquisition = models.URLField(max_length=255, blank=True)
  activation = models.PositiveIntegerField()
  picture_activation = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_activation = models.URLField(max_length=255, blank=True)
  retention = models.PositiveIntegerField()
  picture_retention = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_retention = models.URLField(max_length=255, blank=True)
  revenue = models.PositiveIntegerField()
  picture_revenue = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_revenue = models.URLField(max_length=255, blank=True)  
  referral = models.PositiveIntegerField()
  picture_referral = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_referral = models.URLField(max_length=255, blank=True)
  note = RichTextField(blank=True)
  datetime = models.DateTimeField(default=timezone.now)

  def get_absolute_url(self):
    return reverse('startup-detail', args=[str(self.startup.slug)])

templates/mentor/add_task.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
<div class="container">
    <div class="card">
        <div class="card-header">
          <h3 class="title">Add Task {{mentor.slug}}</h3>
        </div>
        <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <div class="card-action">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </form>
    </div>
       
    </div>
</div>
</div>
{% endblock content %}

templates/mentor/generate-pdf.html
<head>
    <link href="/static/css/dashboard.css" rel="stylesheet" />
    <style>
        .row {
            display: table;
            width: 100%;
        }

        .col-lg-2 {
            padding: 1rem;
            display: table-cell;
            text-align: center;
            width: 20%;
        }

        .col-lg-4 {
            padding: 1rem;
            display: table-cell;
            text-align: center;
            width: 33%;
        }

        .col-lg-10 {
            padding: 1rem;
            display: table-cell;
            text-align: center;
            width: 80%;
        }

        .card {
            background-color: #fff;
            background-clip: border-box;
            border: 1px solid rgba(0, 40, 100, 0.12);
            border-radius: 3px;
        }
        .card-header {
            display: block;
        }

        h1,
        .h1 {
            font-size: 2rem;
        }

        h2,
        .h2 {
            font-size: 1.75rem;
        }

        h3,
        .h3 {
            font-size: 1.5rem;
        }

        h4,
        .h4 {
            font-size: 1.125rem;
        }

        h5,
        .h5 {
            font-size: 1rem;
        }

        h6,
        .h6 {
            font-size: 0.875rem;
        }

        .list-unstyled {
            list-style: none;
            padding: 1rem;
        }

        .list-separated-item {
            padding: 1rem 0;
        }
        
        .list-separated-item:last-child {
            padding-bottom: 0;
        }
        
        .list-separated-item {
            border-top: 1px solid rgba(0, 40, 100, 0.12);
        }
        
        .list-separated-item:first-child {
            padding-top: 0;
            border-top: none;
        }
    </style>
</head>

<body>
    <div class="my-3 my-md-5">
        <div style="background:white">
            <h4 class="page-title" style="text-align:right">Mentor: {{object.mentor}}</h4>
            <h1 class="title" style="text-align: center">Startup Success Report</h4>
                <hr style="color: rgba(0, 40, 100,0.12)">
        </div>
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h4>Feedback's Average</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <br>
                        <div class="col-lg-4">
                            <div class="text-center">
                                <div class="card-body">
                                    <h5 class="card-title color-primary">Communication</h5>
                                    <h1 class="card-text color-primary">{{object.communication_avg.communication_grade__avg}}</h1>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="text-center">
                                <div class="card-body">
                                    <h5 class="card-title color-primary">Relevance</h5>
                                    <h1 class="card-text color-primary">{{object.relevance_avg.relevance_grade__avg}}</h1>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="text-center">
                                <div class="card-body">
                                    <h5 class="card-title color-primary">Helpfullness</h5>
                                    <h1 class="card-text color-primary">{{object.helpfullness_avg.helpfullness_grade__avg}}</h1>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            <div class="card">
                <div class="card-header">
                    <h4>List of mentorings </h4>
                </div>
                <div class="card-body o-auto">
                    <ul class="list-unstyled list-separated">
                        {% for mentoring in object.mentoring_set.all %}
                        <li class="list-separated-item">
                            <div class="card-group row">
                                <div class="col-lg-2">
                                    <div class="card-body text-center">
                                        <span>{{mentoring.datetime}}</span>
                                        <br>
                                    </div>
                                </div>
                                <div class="col-lg-10">
                                    <div class="row">
                                        <div class="card-body col-lg-10">
                                            <h5 class="card-title">{{mentoring.title}}</h5>
                                            <p class="card-text">{{mentoring.mentor_notes}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>

templates/mentor/mentor-update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
    <div class="container">
     
        <div class="card">
     
            <div class="card-header">
                <h3 class="title">Edit Profile</h3>
            </div>
     
            <div class="card-body">
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="from-group row ">
                        <div class="col-6">
                            
                            <div class="card-content">
                                {{ form|crispy}}
                            </div>
                
                            <div class="card-action">
                                <input type="submit" value="Update" class="btn btn-primary"/>
                            </div>
                        
                        </div>
                    </div>
                </form>
            </div>
       
        </div>
    
    </div>
</div>

{% endblock %}

templates/mentor/mentor.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}StartupSuccess{% endblock %}

{% block content %}
{% load group_filter %}

<div class="my-3 my-md-5">
  <!-- container -->
  <div class="container">
    <!-- header -->
    <div class="page-header">
      <h1 class="page-title">Mentor</h1>
    </div>
  <!-- end header -->
  
  <!--List mentor-->
    <div class="row">

      <div class="col-lg-12">
        <div class="card">
    
          <!--card header-->
          <div class="card-header">
            <div class="card-title">List of mentors</div>
            <div class="card-options">
              <form action="">
                <div class="input-group">
                  <input type="text" class="form-control form-control-sm" placeholder="Search something..." name="s">
                  <span class="input-group-btn ml-2">
                    <button class="btn btn-sm btn-default" type="submit">
                      <span class="fe fe-search"></span>
                    </button>
                  </span>
                </div>
              </form>
            </div>
          </div>
          <!--end card header-->
          <div class="card-body">
            {% if mentors  %}
            <div class="row">
              {% for mentor in mentors %}
              <div class="col-lg-3">
                <div class="card">

                  {% if mentor.mentor.profile.header_image %}
                  <div class="widget-header" style="background-image: url('/media/{{mentor.mentor.profile.header_image}}')"></div>
                  {% else %}
                  <div class="widget-header" style="background-image: url(/static/demo/photos/david-klaasen-54203-500.jpg);"></div>
                  {% endif %}
                  
                  {% comment %} <div class="card-body text-center {% if mentor.mentor.profile.nickname == bestMentor.mentoring.mentor.mentor.profile.nickname %} best {% endif %}"> {% endcomment %}
                  
                  <div class="card-body text-center ">
                
                    {% if mentor.mentor.profile.picture %}
                    <img alt="Profile Picture" src="{{mentor.mentor.profile.picture.url}}" class="widget-img avatar img-border-light">
                    {% else %}
                     <img alt="Profile Picture" src="../static/demo/faces/male/user.png" class="widget-img avatar img-border-light">
                    {% endif %}

                    <br>
                    {% comment %} <a href="{% url 'mentor-detail' pk=mentor.id %}"> m</a> {% endcomment %}
                    {% comment %} {{mentor}} {% endcomment %}
                    <a href="{% url 'mentor-detail' pk=mentor.id %}">
                        <h4 class="card-title">{{mentor.mentor}}</h4>
                    </a>
                    <br>
                    <p class="mb-4">
                      {{mentor.mentor.profile.bio }}
                    </p>
                    {% if mentor.mentor.profile.experiencedata_set.all is None %}
                    <h6 class="text-uppercase">Company|Experience</h6>                                        
                    <h6 class="card-subtitle text-uppercase">Undefined</h6>
                    {% else %}
                    {% for experience in mentor.mentor.profile.experiencedata_set.all %}
                    {% if forloop.last %}
                    <h6 class="text-uppercase">{{experience.title}} AT {{experience.company}} </h6>
                    {% endif %}
                    {% endfor %}
                    {% endif %}
                    
                    <hr>
                    <h6 class="text-center text-uppercase">Skills</h6>
                    <div class="row justify-content-md-center">
                      <div class="col-5">
                      {% if mentor.mentor.profile.skilldata_set.all is None %}
                      <h6 class="card-subtitle text-uppercase">Undefined</h6>
                      {% else %}
                        <div class="row">
                      {% for skill in mentor.mentor.profile.skilldata_set.all %}
                            <h6>{{skill.name}}</h6>
                      {% endfor %}
                        </div>
                      {% endif %}
                      </div>
                    </div>
                  </div>

                </div>
              </div>
              {% endfor %}
            </div>
            {% else %}
            <h4 class="text-center text-muted" >Data is empty</h4>
            {% endif %}
          </div>
       

           <!--pagination-->
           
           {% if is_paginated %}
           <div class="card-footer">
             <div class="row justify-content-md-center">
               <div class="pagination">
                 <div class="hint-text page-links">
                   <ul class="pagination">
                   {% if page_obj.has_previous %}
                     <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link"><i class="fa fa-angle-double-left"></i></a></li>
                     <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link page-current">{{ page_obj.previous_page_number }} </a></li>
                   {% endif %}
                     <li class="page-item"><a href="#" class="page-link page-current">{{ page_obj.number }} </a></li>
          
                   {% if page_obj.has_next %}
                     <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link page-current">{{ page_obj.next_page_number }} </a></li>
                     <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link"><i class="fa fa-angle-double-right"></i></a></li>
                   {% endif %} 
                   </ul>
                 </div>
               </div>
             </div>
           </div>
           {% endif %} 
            <!--end pagination-->    

      
        </div>
      </div>
    </div>
  <!--end list mentor-->
  </div>
  <!-- end container -->
</div>
{% endblock %}

templates/mentor/mentor_add_mentoring.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
<div class="container">
    <div class="card">
        <div class="card-header">
          <h3 class="title">Add Mentoring {{mentor.slug}}</h3>
        </div>
        <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <div class="card-action">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </form>
    </div>
       
    </div>
</div>
</div>
{% endblock content %}

templates/mentor/mentor_add_note.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
<div class="container">
    <div class="card">
        <div class="card-header">
          <h3 class="title">Add Mentoring Note {{mentor.slug}}</h3>
        </div>
        <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <div class="card-action">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </form>
    </div>
       
    </div>
</div>
</div>
{% endblock content %}