startupsuccess/urls.py
"""startupsuccess URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    # 1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
# date = timezone.now()
#   print()
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from config.views import *
from ecosystem.views import *
from journal.views import *

# from material.admin import urls

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('accounts/', include('allauth.urls')),

        path('__debug__/', include(debug_toolbar.urls)),

        # path('profile/', MentorProfileDetailView.as_view(), name='myprofile'),
        # path('profile/<slug>/bio/add/', ProfileBio.as_view(), name='profile-bio'),
        
        #new user
        path('profile/<slug>/create', CreateProfile.as_view(), name='profile_create'),
        path('profile/<slug>/experience/', CreateProfileExperience.as_view(), name='profile_create_experience'),
        path('profile/<slug>/education/', CreateProfileEducation.as_view(), name='profile_create_education'),
        path('profile/<slug>/skill/', CreateProfileSkill.as_view(), name='profile_create_skill'),
        
        path('entities-role/', RoleEntitiesView.as_view(), name='role-entities'),
        path('mentor/add/', MentorAdd.as_view(), name='mentor-add'),
        path('mentor/qualification/', MentorQualification.as_view(), name='qualification_mentor'),
        path('mentor/qualification/add/', MentorQualificationAnswer.as_view(), name='qualification_add_mentor'),
        path('mentor/qualification/status/', MentorQualificationStatus.as_view(), name='qualification_status_mentor'),
        path('startup-role/', RoleStartupView.as_view(), name='role-startup'),
        path('startup/add/', StartupAdd.as_view(), name='startup-add'),


        #profile
        path('profile/<slug>/', ProfileView.as_view(), name='myprofile'),
        path('profile/<slug>/update/', ProfileUpdate.as_view(), name='profile-update-profile'),
        path('profile/<slug>/experience/add/', ProfileExperienceAdd.as_view(), name='profile_add_experience'),
        path('profile/<slug>/<pk>/experience/update/', ProfileExperienceUpdate.as_view(), name='profile_update_experience'),
        path('profile/<slug>/<pk>/experience/delete/', ProfileExperienceDelete.as_view(), name='profile_delete_experience'),
        path('profile/<slug>/education/add/', ProfileEducationAdd.as_view(), name='profile_add_education'),
        path('profile/<slug>/<pk>/education/update/', ProfileEducationUpdate.as_view(), name='profile_update_education'),
        path('profile/<slug>/<pk>/education/delete/', ProfileEducationDelete.as_view(), name='profile_delete_education'),
        path('profile/<slug>/skill/add', ProfileSkillAdd.as_view(), name='profile_add_skill'),
        path('profile/<slug>/<pk>/skill/update/', ProfileSkillUpdate.as_view(), name='profile_update_skill'),
        path('profile/<slug>/<pk>/skill/delete/', ProfileSkillDelete.as_view(), name='profile_delete_skill'),

        # path('profile/<slug>/update', ProfileUserUpdate.as_view(), name='profile-update-user'),


        #schedule
        path('schedule/', ScheduleListView.as_view(), name='schedule-list'),
        path('schedule/update/mentor/<slug>/<pk>/', ScheduleMentorAttendanceUpdate.as_view(), name='schedule_update_attendance_mentor'),
        path('schedule/update/startup/<slug>/<pk>/', ScheduleStartupAttendanceUpdate.as_view(), name='schedule_update_attendance_startup'),

        #mentoring
        path('mentor/<slug>/mentoring/add', MentorMentoringAdd.as_view(), name='mentor-add-mentoring'),
        path('mentor/<slug>/<pk>/mentoring/note', MentorMentoringNote.as_view(), name='mentoring_add_note'),
        path('startup/<slug>/<pk>/update/mentoring', StartupUpdateMentoring.as_view(), name='startup-update-mentoring'),

        #feedback
        path('mentoring/<pk>/feedback/add/startup/', StartupFeedbackForMentor.as_view(), name='startup-feedback'),
        path('mentoring/<pk>/feedback/add/mentor/', MentorFeedbackForStartup.as_view(), name='mentor-feedback'),

        #task
        path('mentor/<pk>/task/add', MentorTaskAdd.as_view(), name='mentor_add_task'),



        # path('startup/<slug>/mentoring/add', StartupMentoringAdd.as_view(), name='startup-add-mentoring'),



        # path('profile/<slug>/', ProfileExperienceAdd.as_view(), name='profile_experience_add'),

        # path('profile/<slug>/', ProfileView.as_view(), name='myprofile'),
        path('profile/<slug>/<pk>/', ApprovalMemberView.as_view(), name='approval-startup'),
        #2
        path('mentor/', MentorListView.as_view(), name='mentor-list'),
        path('mentor/<slug>/add/', MentorUpdateSkillsView.as_view(), name='mentor-update-skills'),
        #3
        # path('mentor/<slug>/', MentorDetailView.as_view(), name='mentor-detail'),
        path('mentor/<pk>/', MentorDetailView.as_view(), name='mentor-detail'),

        #4
        path('mentor/<slug>/generate-pdf', GenerateMentorPdf.as_view(), name='generate-mentor-pdf'),
        path('mentor/<slug>/update/', MentorUpdateView.as_view(), name='mentor-update'),
        path('mentor/<slug>/<pk>/update/mentoring', MentorUpdateMentoring.as_view(), name='mentor-update-mentoring'),
        path('mentor/<slug>/mentoring-detail', MentorMentoringDetail.as_view(), name='mentor-mentoring-detail'),

        path('member/invite/', MemberListView.as_view(), name='member-invite'),
        path('member/invite/<pk>', RequestInviteMemberView.as_view(), name='request-invite'),

        path('startup-role/requestjoin/<slug>', RequestJoinView.as_view(), name='join-startup'),

        path('startup/<slug>/<int:pk>/', ApprovalView.as_view(), name='approval-member' ),
        #0
        #6
        path('startup/', StartupListView.as_view(), name='startup-list'),
        path('startup/<slug>/', StartupDetailView.as_view(), name='startup-detail'),
        path('startup/<slug>/generate-pdf', GenerateStartupPdf.as_view(), name='generate-startup-pdf'),
        path('startup/<slug>/update/', StartupUpdate.as_view(), name='startup-update'),
        path('startup/<slug>/<pk>/mentoring-detail', StartupMentoringDetailView.as_view(), name='startup-mentoring-detail'),
        path('startup/<slug>/<pk>/add/answer-task', StartupMentoringAddTask.as_view(), name='startup-add-mentoring-task'),
        path('startup/<slug>/delete/', StartupDelete.as_view(), name='startup-delete'),
        path('startup/<slug>/add-progress', StartupAddProgress.as_view(), name='startup-add-progress'),
        path('startup/<slug>/<pk>/detail/progress', StartupDetailProgress.as_view(), name='startup-detail-progress'),
        path('startup/<slug>/<pk>/update/progress', StartupUpdateProgress.as_view(), name='startup-update-progress'),
        path('startup/<slug>/<pk>/delete/progress', StartupDeleteProgress.as_view(), name='startup-delete-progress'),
        path('startup/<slug>/<pk>/schedule-detail', StartupScheduleDetailView.as_view(), name='startup-schedule-detail'),

        path('mentoring/', MentoringListView.as_view(), name='mentoring-list'),
        path('mentoring/add/', MentoringCreateView.as_view(), name='mentoring-add'),
        path('mentoring/generate-pdf', GenerateMentoringPdf.as_view(), name='generate-mentoring-pdf'),
        #5
        path('mentoring/<pk>/', MentoringDetailView.as_view(), name='mentoring-detail'),
        path('mentoring/<pk>/attendance/', MentoringAttendance.as_view(), name='mentoring-attendance'),

        path('mentoring/<pk>/feedback', MentoringFeedback.as_view(), name='mentoring-feedback'),
        
        path('mentoring/<pk>/delete/', MentoringDeleteView.as_view(), name='mentoring-delete'),
        path('mentoring/<pk>/update/startup', MentoringUpdateStartupView.as_view(), name='mentoring-update-startup'),
        path('mentoring/<pk>/update/mentor', MentoringUpdateMentorView.as_view(), name='mentoring-update-mentor'),


        #1
        path('', HomeView.as_view(), name='home'),

        path(r'jet/', include('jet.urls', 'jet')),  # Django JET URLS
        # path('')
        path('invitations/', include('invitations.urls', namespace='invitations')),
        path('member/invite/email/', InviteEmailMemberView.as_view(), name='member-invite-email'),


    ]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

journal/models.py
import json
import datetime
import uuid
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.utils.text import slugify
from django.db import models
from django.db.models.signals import m2m_changed
from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.auth.models import User
from django.dispatch import receiver
from allauth.account.signals import user_signed_up
from ckeditor.fields import RichTextField
from util.randomizer import unique_slug_generator, unique_slug_generator_byfield
from config.models import *
from django.urls import reverse


class Scheduling(models.Model):
  program = models.ForeignKey('config.Program', on_delete=models.CASCADE)
  description = RichTextField(blank=True)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ManyToManyField('ecosystem.Startup')
  venue  = models.CharField(max_length=255, default='Common Room')
  capacity = models.CharField(max_length=255, blank=True)
  datetime = models.DateTimeField(default=timezone.now)
  location = models.CharField(max_length=255, default='EDS')
  status_mentor = models.BooleanField(default=False)
  status_startup = models.BooleanField(default=False)
  created = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.program.name

class Mentoring(models.Model):
  id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
  program = models.ForeignKey('config.Program', on_delete=models.CASCADE)
  datetime = models.DateTimeField(default=timezone.now)
  title = models.CharField(max_length=255)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE, blank=True)
  # mentor_attendance = models.BooleanField(default=True)
  # founder_attendance = models.ManyToManyField('ecosystem.StartupMember', related_name='founder_attendance', blank=True)
  mentor_question = RichTextField(blank=True)
  startup_answer = RichTextField(blank=True)
  startup_question = RichTextField(blank=True)
  mentor_answer = RichTextField(blank=True)
  mentor_notes = RichTextField(blank=True)
  startup_notes = RichTextField(blank=True)
  location = models.CharField(max_length=255, default='EDS')

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.id)])

  def __str__(self):
      return self.title

class Task(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  mentor = models.ForeignKey('ecosystem.Mentor', on_delete=models.CASCADE)
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE)
  task_for_startup = RichTextField(blank=True)
  startup_assignment_report = RichTextField(blank=True)
  mentor_assignment_feedback = RichTextField(blank=True)
  
  def __str__(self):
    return self.task_for_startup


class FeedbackForMentor(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  communication_grade = models.PositiveIntegerField()
  relevance_grade = models.PositiveIntegerField()
  helpfullness_grade = models.PositiveIntegerField()
  note = RichTextField(blank=True)

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.mentoring.id)])

  # def __str__(self):
  #   return self.note

class FeedbackForStartup(models.Model):
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  communication_grade = models.PositiveIntegerField()
  attitude_grade = models.PositiveIntegerField()
  perseverance_grade = models.PositiveIntegerField()
  note = RichTextField(blank=True)

  def get_absolute_url(self):
    return reverse('mentoring-feedback', args=[str(self.mentoring.id)])


def startupprogress_directory_path(instance, filename):
  return 'startupprogress/{0}/{1}'.format(instance.startup.name,filename)

class StartupProgress(models.Model):
  startup = models.ForeignKey('ecosystem.Startup', on_delete=models.CASCADE)
  mentoring = models.ForeignKey('journal.Mentoring', on_delete=models.CASCADE)
  week = models.PositiveIntegerField()
  acquisition = models.PositiveIntegerField()
  picture_acquisition = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_acquisition = models.URLField(max_length=255, blank=True)
  activation = models.PositiveIntegerField()
  picture_activation = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_activation = models.URLField(max_length=255, blank=True)
  retention = models.PositiveIntegerField()
  picture_retention = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_retention = models.URLField(max_length=255, blank=True)
  revenue = models.PositiveIntegerField()
  picture_revenue = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_revenue = models.URLField(max_length=255, blank=True)  
  referral = models.PositiveIntegerField()
  picture_referral = models.ImageField(blank=True, upload_to=startupprogress_directory_path,)
  url_referral = models.URLField(max_length=255, blank=True)
  note = RichTextField(blank=True)
  datetime = models.DateTimeField(default=timezone.now)

  def get_absolute_url(self):
    return reverse('startup-detail', args=[str(self.startup.slug)])

templates/startup/generate-pdf.html
{% extends 'base.html' %} {% load static i18n %} {% block title %}StartupSuccess{% endblock %} {% block content %}

<div class="my-3 my-md-5">
    <!-- <div style="border:1px solid rgba(0, 40, 100, 0.12); padding: 16px; background:white; border-radius: calc(3px - 1px) calc(3px - 1px) 0 0,"> -->
    <div style="background:white">
        <h4 class="page-title" style="text-align:right">Startup: {{object.name}}</h4>
        <h1 class="title" style="text-align: center">Startup Success Report</h4>
        <hr style="color: rgba(0, 40, 100,0.12)">
    </div>
    <div class="container">
        <div class="card">
            <h3 class="card-title">Weekly Progress</h3>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Date</th>
                            <th scope="col">Acquisition</th>
                            <th scope="col">Activation</th>
                            <th scope="col">Retention</th>
                            <th scope="col">Revenue</th>
                            <th scope="col">Referral</th>
                        </tr>
                    </thead>
                    {% for startup in startupProgress %}
                    <tbody>
                        <tr>
                            <th scope="row">{{startup.datetime|date:'Y-m-d'}}</th>
                            <td>{{startup.acquisition}}</td>
                            <td>{{startup.activation}}</td>
                            <td>{{startup.retention}}</td>
                            <td>{{startup.revenue}}</td>
                            <td>{{startup.referral}}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="card">
            <h3 class="card-title">Monthly Progress</h3>
            <div class="card-body">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Month</th>
                            <th scope="col">Acquisition</th>
                            <th scope="col">Activation</th>
                            <th scope="col">Retention</th>
                            <th scope="col">Revenue</th>
                            <th scope="col">Referral</th>
                        </tr>
                    </thead>
                    {% for startup in startupProgressMonthly reversed %}
                    <tbody>
                        <tr>
                            <th scope="row">{{startup.month|date:'b'}}</th>
                            <td>{{startup.acquisition_sum}}</td>
                            <td>{{startup.activation_sum}}</td>
                            <td>{{startup.retention_sum}}</td>
                            <td>{{startup.revenue_sum}}</td>
                            <td>{{startup.referral_sum}}</td>
                        </tr>
                    </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/startup/newfounder.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}StartupSuccess{% endblock %}

{% block content %}
<h1>New founder</h1>
{% endblock %}

templates/startup/schedule_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% load social_share %}
{% block title %}StartupSuccess{% endblock %}

{% block content %}

<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">Details</h1>
        </div>
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{data_schedule}}</h3>
                    <div class="card-options">
                        <a href="#" class="btn btn-primary btn-sm"><i class="fa fa-comments mr-2"></i>  Feedback</a>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table card-table table-striped table-vcenter">
                        <thead>
                            <tr>
                                <th colspan="2">Speaker</th>
                                <th>Time</th>
                                <th>Location</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="w-1">
                                {% if dataMentoring.mentor.mentor.profile.picture %}
                                    <span class="avatar" style="background-image: url('/media/{{dataMentoring.mentor.mentor.profile.picture}}')"></span>
                                {% else %}
                                    <span class="avatar" style="background-image: url(/static/demo/faces/male/user.png)"></span>
                                {% endif %}

                                    <td>{{dataMentoring.mentor}}</td>
                                    <td class="text-nowrap">{{dataMentoring.datetime}}</td>
                                    <td>{{dataMentoring.location}}</td>
                                          
                                    <td class="w-1"><a href="#" class="btn btn-sm btn-secondary" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><i class="fe fe-upload mr-1"></i> Share</a>
                                    <div class="collapse" id="collapseExample">
                                            {% post_to_twitter "New Mentoring: {{dataMentoring}}. Check it out!" object_or_url "Twitter" %}
                                            {% post_to_facebook  object_or_url "Facebook" %}

                                        </div>
                                    </td>
                                    
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <h3 class="card-title">Description</h3>
                    <p>{{dataMentoring.program.description}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
$(function () {
  $('.example-popover').popover({
    container: 'body'
  })
})
</script>

{% endblock %}

templates/startup/startup.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}StartupSuccess{% endblock %}

{% block content %}
{% comment %} {% load group_filter %} {% endcomment %}

<div class="my-3 my-md-5">
  <!-- container -->
  <div class="container">
    <!-- header -->
    <div class="page-header">
      <h1 class="page-title">Startup</h1>
    </div>

  <!-- end header -->
  <!--List mentor-->
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <!--card header-->
          <div class="card-header">
            <div class="card-title">List of startups</div>
            <div class="card-options">
              <form action="">
                <div class="input-group">
                  <input type="text" class="form-control form-control-sm" placeholder="Search something..." name="s">
                  <span class="input-group-btn ml-2">
                    <button class="btn btn-sm btn-default" type="submit">
                      <span class="fe fe-search"></span>
                    </button>
                     {% comment %} {% if request.user|has_group:"admin" %} {% endcomment %}
                    {% comment %} <a class="btn btn-primary ml-5" href="{% url 'startup-add' %}">Add startup</a> {% endcomment %}
                    {% comment %} {% endif %}           {% endcomment %}
                  </span>
                </div>
              </form>
            </div>
          </div>
          <!--end card header-->
          <div class="card-body">
            {% if object_list %}
            <div class="row">
              {% for startup in object_list %}
              <div class="col-lg-3">
                <div class="card">
                  {% if startup.header_image %}
                  <div class="widget-header" style="background-image: url('/media/{{startup.header_image}}');"></div>
                  {% else %}
                  <div class="widget-header" style="background-image: url('../static/demo/photos/adrian-infernus-281832-1500.jpg');"></div>
                  {% endif %}
                  <div class="widget-body text-center {% if startup.name == bestStartup.startup__name %} best {% endif %}">
                    {% if startup.picture %}
                    <img alt="Profile Picture" class="widget-img avatar img-border-light" src="{{startup.picture.url}}">
                    {% else %}
                    <img alt="Profile Picture" class="widget-img avatar img-border-light" src="../static/demo/faces/male/user.png">
                    {% endif %}
                    <a href="{% url 'startup-detail' slug=startup.slug %}">
                      <h4 class="card-title">{{startup.name}}</h4>
                    </a>
                    <br>
            
                    <h6 class="card-subtitile text-uppercase">Last mentoring sessions: {{startup.startupprogress_set.all.0.week}} wk</h6>
                    <div class="row justify-content-md-center text-uppercase">
                      <div class="col-6">
                        <small>revenue</small>
                        <br>
                        <span>{{startup.total_revenue}}</span>  
                      </div>   
                      <div class="col-6">
                        <small>acquisition</small>
                        <br>
                        <span>{{startup.total_acquisition}}</span>
                      </div>
                    </div>
                    <hr>
                    <h6 class="card-subtitile text-center text-uppercase">Action Items</h6>
                    <div class="row justify-content-md-center text-uppercase">
                      <div class="col-6">
                        <small>Activation</small>
                        <br>
                        <span>{{startup.total_activation}}</span>
                      </div>
                    </div>
                  </div>
                </div>
              {% comment %} </a> {% endcomment %}
              </div>
              {% endfor %}
            </div>
            {% else %}
            <h4 class="text-center text-muted" > Data is empty </h4>
            {% endif %}
          </div>
          <!--pagination-->
          {% if is_paginated %}
          <div class="card-footer">
            <div class="row">
              <div class="col-lg-12 ">
                <div class="hint-text page-links">
                  <ul class="pagination justify-content-center">
                    {% comment %} {{page_obj.paginator.page_range}} {% endcomment %}
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                        <i class="fa fa-angle-double-left"></i>
                      </a>
                    </li>
                    <li class="page-item">
                      <a href="?page={{ page_obj.previous_page_number}}" class="page-link">{{ page_obj.previous_page_number }}</a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                      <span class="page-link page-current">{{ page_obj.number }} </span>
                    </li>
                    {% if page_obj.has_next %}
                    <li class="page-item">
                      <a href="?page={{ page_obj.next_page_number}}" class="page-link">{{ page_obj.next_page_number }}</a>
                    </li>
                    <li class="page-item">
                      <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                        <i class="fa fa-angle-double-right"></i>
                      </a>
                    </li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            </div>
          </div>
          {% endif %}                  
    <!--end pagination-->
        </div>
      </div>
    </div>
  <!--end list mentor-->
  </div>
  <!-- end container -->
</div>
{% endblock %}

templates/startup/startup_add_progress.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
<div class="container">
    <div class="card">
        <div class="card-header">
          <h3 class="title">Add Progress {{startup.title}}</h3>
        </div>
        <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <div class="card-action">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </form>
    </div>
       
    </div>
</div>
</div>
{% endblock content %}

templates/startup/startup_add_task_mentoring.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
<div class="container">
    <div class="card">
        <div class="card-header">
          <h3 class="title">Add Task {{startup.title}}</h3>
        </div>
        <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <div class="card-action">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </form>
    </div>
       
    </div>
</div>
</div>
{% endblock content %}

templates/startup/startup_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
          <h3 class="title">Create New Startup</h3>
      </div>
      <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Create" />
        </form>
      </div>
    </div>
  </div>
  
{% endblock %}

templates/startup/startup_new.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}StartupSuccess{% endblock %}
{% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                Choose Startup
            </h1>
        </div>
        <div class="row">
            <div class="col-sm-6 col-lg-3">
                <div class="card">
                    <div class="card-body text-center">
                        <div class="card-category">Create</div>
                        <div class="display-3 my-4">New Startup</div>
                        <div class="text-center mt-6">
                            <a href="{% url 'startup-add' %}" class="btn btn-secondary btn-block">Create</a>
                        </div>
                    </div>
                </div>
            </div>
            {% for startup in startup %}
            <div class="col-sm-6 col-lg-3">
                <div class="card">
                    <div class="card-status bg-green"></div>
                    <div class="card-body text-center">
                        <div class="card-category">Join</div>
                        <div class="display-3 my-4">{{startup}}</div>
                        <div class="text-center mt-6">
                            <a href="{% url 'join-startup' slug=startup.slug %}" class="btn btn-green btn-block">Request Join</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

templates/startup/startup_progress_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

templates/startup/startup_update_mentoring.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="my-3 my-md-5">
<div class="container">
    <div class="card">
        <div class="card-header">
          <h3 class="title">Update Mentoring {{startup.title}}</h3>
        </div>
        <div class="card-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <div class="card-action">
                <input type="submit" class="btn btn-primary" value="Save">
            </div>
        </form>
    </div>
       
    </div>
</div>
</div>
{% endblock content %}